// CORBA to JAVA Data Types
// long     --> int
// string   --> string
// sequence --> array

module common {
	interface BoxOffice {
	
	    exception invalid_customer {};
	    exception invalid_event {};
	    
		typedef sequence<string> events;

		void reserve(in long customer_id, in string show_id, in long quantity) raises (invalid_customer, invalid_event);
		void cancel(in long customer_id, in string show_id, in long qty) raises (invalid_customer, invalid_event);
		long show(in string show_id) raises (invalid_event);
		events allEvents();
		void createEvent(in string event_id, in string title, in long capacity) raises (invalid_event);
		void exchange(in long customer_id, in string reserved_event_id, in long reserved_tickets, in string desired_event_id, in long desired_tickets) raises (invalid_customer, invalid_event);
		boolean canExchange(in long customer_id, in string show_id, in long no_tickets) raises (invalid_customer, invalid_event);
		void shutdown();
	};
};
