package common.BoxOfficePackage;


/**
* common/BoxOfficePackage/eventsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ben/workspace/soen423.a2/src/idl/boxoffice.idl
* Monday, October 31, 2011 11:37:29 PM EDT
*/

public final class eventsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public eventsHolder ()
  {
  }

  public eventsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = common.BoxOfficePackage.eventsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    common.BoxOfficePackage.eventsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return common.BoxOfficePackage.eventsHelper.type ();
  }

}
