package common.BoxOfficePackage;


/**
* common/BoxOfficePackage/invalid_customer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ben/workspace/soen423.a2/src/idl/boxoffice.idl
* Monday, October 31, 2011 8:22:01 PM EDT
*/

public final class invalid_customer extends org.omg.CORBA.UserException
{

  public invalid_customer ()
  {
    super(invalid_customerHelper.id());
  } // ctor


  public invalid_customer (String $reason)
  {
    super(invalid_customerHelper.id() + "  " + $reason);
  } // ctor

} // class invalid_customer
