package common.BoxOfficePackage;


/**
* common/BoxOfficePackage/invalid_event.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ben/workspace/soen423.a2/src/idl/boxoffice.idl
* Sunday, October 30, 2011 10:14:35 PM EDT
*/

public final class invalid_event extends org.omg.CORBA.UserException
{

  public invalid_event ()
  {
    super(invalid_eventHelper.id());
  } // ctor


  public invalid_event (String $reason)
  {
    super(invalid_eventHelper.id() + "  " + $reason);
  } // ctor

} // class invalid_event
