package common;


/**
* common/_BoxOfficeStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ben/workspace/soen423.a2/src/idl/boxoffice.idl
* Sunday, October 30, 2011 10:14:35 PM EDT
*/

public class _BoxOfficeStub extends org.omg.CORBA.portable.ObjectImpl implements common.BoxOffice
{

  public void reserve (int customer_id, String show_id, int quantity) throws common.BoxOfficePackage.invalid_customer, common.BoxOfficePackage.invalid_event
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("reserve", true);
                $out.write_long (customer_id);
                $out.write_string (show_id);
                $out.write_long (quantity);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:common/BoxOffice/invalid_customer:1.0"))
                    throw common.BoxOfficePackage.invalid_customerHelper.read ($in);
                else if (_id.equals ("IDL:common/BoxOffice/invalid_event:1.0"))
                    throw common.BoxOfficePackage.invalid_eventHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                reserve (customer_id, show_id, quantity        );
            } finally {
                _releaseReply ($in);
            }
  } // reserve

  public void cancel (int customer_id, String show_id, int qty) throws common.BoxOfficePackage.invalid_customer, common.BoxOfficePackage.invalid_event
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("cancel", true);
                $out.write_long (customer_id);
                $out.write_string (show_id);
                $out.write_long (qty);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:common/BoxOffice/invalid_customer:1.0"))
                    throw common.BoxOfficePackage.invalid_customerHelper.read ($in);
                else if (_id.equals ("IDL:common/BoxOffice/invalid_event:1.0"))
                    throw common.BoxOfficePackage.invalid_eventHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                cancel (customer_id, show_id, qty        );
            } finally {
                _releaseReply ($in);
            }
  } // cancel

  public void show (String show_id, org.omg.CORBA.IntHolder showID) throws common.BoxOfficePackage.invalid_event
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("show", true);
                $out.write_string (show_id);
                $in = _invoke ($out);
                showID.value = $in.read_long ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:common/BoxOffice/invalid_event:1.0"))
                    throw common.BoxOfficePackage.invalid_eventHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                show (show_id, showID        );
            } finally {
                _releaseReply ($in);
            }
  } // show

  public void allEvents (common.BoxOfficePackage.eventsHolder all_shows)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("allEvents", true);
                $in = _invoke ($out);
                all_shows.value = common.BoxOfficePackage.eventsHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                allEvents (all_shows        );
            } finally {
                _releaseReply ($in);
            }
  } // allEvents

  public void createEvent (String event_id, String title, int capacity) throws common.BoxOfficePackage.invalid_event
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createEvent", true);
                $out.write_string (event_id);
                $out.write_string (title);
                $out.write_long (capacity);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:common/BoxOffice/invalid_event:1.0"))
                    throw common.BoxOfficePackage.invalid_eventHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                createEvent (event_id, title, capacity        );
            } finally {
                _releaseReply ($in);
            }
  } // createEvent

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:common/BoxOffice:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _BoxOfficeStub
