package common;

/**
* common/BoxOfficeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ben/workspace/soen423.a2/src/idl/boxoffice.idl
* Sunday, October 30, 2011 10:14:35 PM EDT
*/

public final class BoxOfficeHolder implements org.omg.CORBA.portable.Streamable
{
  public common.BoxOffice value = null;

  public BoxOfficeHolder ()
  {
  }

  public BoxOfficeHolder (common.BoxOffice initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = common.BoxOfficeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    common.BoxOfficeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return common.BoxOfficeHelper.type ();
  }

}
