package common;


/**
* common/BoxOffice.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ben/workspace/soen423.a2/src/idl/boxoffice.idl
* Tuesday, November 8, 2011 3:54:34 PM EST
*/

public interface BoxOffice extends BoxOfficeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BoxOffice
