package common;


/**
* common/BoxOfficeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ben/workspace/soen423.a2/src/idl/boxoffice.idl
* Sunday, October 30, 2011 10:14:35 PM EDT
*/

public interface BoxOfficeOperations 
{
  void reserve (int customer_id, String show_id, int quantity) throws common.BoxOfficePackage.invalid_customer, common.BoxOfficePackage.invalid_event;
  void cancel (int customer_id, String show_id, int qty) throws common.BoxOfficePackage.invalid_customer, common.BoxOfficePackage.invalid_event;
  void show (String show_id, org.omg.CORBA.IntHolder showID) throws common.BoxOfficePackage.invalid_event;
  void allEvents (common.BoxOfficePackage.eventsHolder all_shows);
  void createEvent (String event_id, String title, int capacity) throws common.BoxOfficePackage.invalid_event;
} // interface BoxOfficeOperations
