package common;


/**
* common/BoxOfficePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ben/workspace/soen423.a2/src/idl/boxoffice.idl
* Sunday, October 30, 2011 8:30:25 PM EDT
*/

public class BoxOfficePOATie extends BoxOfficePOA
{

  // Constructors

  public BoxOfficePOATie ( common.BoxOfficeOperations delegate ) {
      this._impl = delegate;
  }
  public BoxOfficePOATie ( common.BoxOfficeOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public common.BoxOfficeOperations _delegate() {
      return this._impl;
  }
  public void _delegate (common.BoxOfficeOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void reserver (String msg)
  {
    _impl.reserver(msg);
  } // reserver

  private common.BoxOfficeOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class BoxOfficePOATie
