package common;


/**
* common/BoxOfficePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ben/workspace/soen423.a2/src/idl/boxoffice.idl
* Sunday, October 30, 2011 10:14:35 PM EDT
*/

public class BoxOfficePOATie extends BoxOfficePOA
{

  // Constructors

  public BoxOfficePOATie ( common.BoxOfficeOperations delegate ) {
      this._impl = delegate;
  }
  public BoxOfficePOATie ( common.BoxOfficeOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public common.BoxOfficeOperations _delegate() {
      return this._impl;
  }
  public void _delegate (common.BoxOfficeOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void reserve (int customer_id, String show_id, int quantity) throws common.BoxOfficePackage.invalid_customer, common.BoxOfficePackage.invalid_event
  {
    _impl.reserve(customer_id, show_id, quantity);
  } // reserve

  public void cancel (int customer_id, String show_id, int qty) throws common.BoxOfficePackage.invalid_customer, common.BoxOfficePackage.invalid_event
  {
    _impl.cancel(customer_id, show_id, qty);
  } // cancel

  public void show (String show_id, org.omg.CORBA.IntHolder showID) throws common.BoxOfficePackage.invalid_event
  {
    _impl.show(show_id, showID);
  } // show

  public void allEvents (common.BoxOfficePackage.eventsHolder all_shows)
  {
    _impl.allEvents(all_shows);
  } // allEvents

  public void createEvent (String event_id, String title, int capacity) throws common.BoxOfficePackage.invalid_event
  {
    _impl.createEvent(event_id, title, capacity);
  } // createEvent

  private common.BoxOfficeOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class BoxOfficePOATie
