package common;


/**
* common/BoxOfficeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ben/workspace/soen423.a2/src/idl/boxoffice.idl
* Sunday, October 30, 2011 8:30:25 PM EDT
*/

public interface BoxOfficeOperations 
{
  void reserver (String msg);
} // interface BoxOfficeOperations
