package common;


/**
* common/BoxOfficePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ben/workspace/soen423.a2/src/idl/boxoffice.idl
* Tuesday, November 8, 2011 3:54:34 PM EST
*/

public class BoxOfficePOATie extends BoxOfficePOA
{

  // Constructors

  public BoxOfficePOATie ( common.BoxOfficeOperations delegate ) {
      this._impl = delegate;
  }
  public BoxOfficePOATie ( common.BoxOfficeOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public common.BoxOfficeOperations _delegate() {
      return this._impl;
  }
  public void _delegate (common.BoxOfficeOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void reserve (int customer_id, String show_id, int quantity) throws common.BoxOfficePackage.invalid_customer, common.BoxOfficePackage.invalid_event
  {
    _impl.reserve(customer_id, show_id, quantity);
  } // reserve

  public void cancel (int customer_id, String show_id, int qty) throws common.BoxOfficePackage.invalid_customer, common.BoxOfficePackage.invalid_event
  {
    _impl.cancel(customer_id, show_id, qty);
  } // cancel

  public int show (String show_id) throws common.BoxOfficePackage.invalid_event
  {
    return _impl.show(show_id);
  } // show

  public String[] allEvents ()
  {
    return _impl.allEvents();
  } // allEvents

  public void createEvent (String event_id, String title, int capacity) throws common.BoxOfficePackage.invalid_event
  {
    _impl.createEvent(event_id, title, capacity);
  } // createEvent

  public void exchange (int customer_id, String reserved_event_id, int reserved_tickets, String desired_event_id, int desired_tickets) throws common.BoxOfficePackage.invalid_customer, common.BoxOfficePackage.invalid_event
  {
    _impl.exchange(customer_id, reserved_event_id, reserved_tickets, desired_event_id, desired_tickets);
  } // exchange

  public int getUDPPort ()
  {
    return _impl.getUDPPort();
  } // getUDPPort

  public String getUDPHost ()
  {
    return _impl.getUDPHost();
  } // getUDPHost

  public void shutdown ()
  {
    _impl.shutdown();
  } // shutdown

  private common.BoxOfficeOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class BoxOfficePOATie
